### ISSUE TITLE
GUI - Erstellen

### ISSUE THREAD

**Issue by MninaTB** [MninaTB/AE_Quiz_Projekt24#5]
```
- [ ] GUI Screens besprechen - Mockups #18
- [ ] Rohe Implementation #20 
- [ ] Rohe Implementation - Bearbeitungsscreen #54
- [ ] GUI Architektur - Strukturierung #62 
- [ ] Logik GUI #65 
```
